import "@/app/globals.css";
import { Navigation } from "@/components/shared/navigation.component";
import HomeContextProvider from "@/context/home.context";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        <HomeContextProvider>
          <section className=" h-full w-full border-[2rem] border-primary bg-primary ">
            <div className="h-full w-full border-[2rem] border-primary-foreground  bg-primary-foreground rounded-2xl">
              <div className="h-full w-full border min-h-screen min-w-screen p-4 bg-white rounded-2xl">
                <nav className="font-manrope w-full h-full">
                  <Navigation />
                </nav>
                <main>{children}</main>
                <footer>this is a footer</footer>
              </div>
            </div>
          </section>
        </HomeContextProvider>
      </body>
    </html>
  );
}
