import "@/app/globals.css";
import HomeContextProvider from "@/context/home.context";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <HomeContextProvider>
          <section className="min-h-screen h-full w-full border-[2rem] border-[#8D0E57] ">
            <section className="h-full w-full border-[2rem] border-[#C792AF]  ">
              <section className="h-full w-full border  rounded-xl min-h-screen p-4">
                {children}
              </section>
            </section>
          </section>
        </HomeContextProvider>
      </body>
    </html>
  );
}
